module.exports = {
    "blindblocart": ["@BlindBlocArtJerry"],
    "caleosblocks": ["@foflexity"],
    "cryptosuviio": ["@SolariusFI"],
    "eosphereiobp": ["@rossco99"],
    "eosriobrazil": ["@igorls"],
    "gyftieblocks ": ["@wmw509"],
    "infinitybloc": ["@Infinityblocio"],
    "kainosblkpro": ["@HartParr"],
    "southafrica1": ["@rorymapstone"],
    "teamgreymass": ["@jestagram"],
    "teleologytls": ["@ryanlj"],
    "telosarabia1": ["@basel_alkaddoumi"],
    "telosboston1": ["@telosboston"],
    "telosglobal1": ["@kquainta"],
    "telosgreenbp": ["@sukeshtedla"],
    "teloskitchen": ["@dappdever"],
    "telosmadrid1": ["@Mikelito74"],
    "telosmiamibp": ["@qubicles"],
    "telosuknodes": ["@EOS_Nottingham"],
    "telosunlimit": ["@macanico"],
    "theteloscope": ["@LuisMeijueiro"],
    "theteloscrew": ["@captaincryptohd"],
    "persiantelos": ["@Parsieos","@aliiraghamii"],
    "votetelosusa": ["@EOSUSA_Michael"],

}
