module.exports = {
    "amsterdam"   : ["@cc32d9","@blessendor"],
    "bp.adex"     : ["@Avm07"],
    "bp.any"      : ["@Ali_Raghami"],
    "bp.boid"     : ["@I_Seth","@boidcom"],
    "caleosblocks": ["@foflexity"],
    "creativblock": ["@AjinkyaJagtap"],
    "cryptosuviio": ["@SolariusFI"],
    "dappetizerbp": ["@bransdotcom"],
    "eosphereiobp": ["@rossco99"],
    "eosriobrazil": ["@igorls"],
    "greymass"    : ["@jestagram"],
    "gyftieblocks": ["@wmw509"],
    "infinitybloc": ["@Infinityblocio"],
    "kainosblkpro": ["@HartParr"],
    "ledgerwisete": ["@jorfermo"],
    "mosaicblocks": ["@TelosHR"],
    "southafrica1": ["@rorymapstone","@Andreas86"],
    "sentnlagents": ["ankh2054"],
    "swapsicledex": ["@firepol"],
    "teamgreymass": ["@jestagram"],
    "teleologytls": ["@ryanlj"],
    "telosarabia1": ["@basel_alkaddoumi"],
    "telosboston1": ["@telosboston"],
    "teloscentral": ["@Telos_Central"],
    "telosgermany": ["@StefanGenerEOS","@RalfWeinand"],
    "telosgreenbp": ["@sukeshtedla"],
    "tlosimperabp": ["@zaragast"],
    "teloskitchen": ["@dappdever"],
    "teloskoreabp": ["@t_e_o"],
    "telosmadrid1": ["@Mikelito74"],
    "telosmiamibp": ["@qubicles"],
    "telosuknodes": ["@theblockstalk"],
    "telosunlimit": ["@macanico"],
    "theteloscope": ["@LuisMeijueiro"],
    "theteloscrew": ["@captaincryptohd"],
    "persiantelos": ["@Parsieos","@Vahidhossa"],
    "votetelosusa": ["@EOSUSA_Michael"],  
    "votedutcheos": ["@ArjenDT"],
    "telosindiabp": ["@thatzprem"],
    "telosculture": ["@BrianT7", "@MiloSx7"],
    "fortisblocks": ["@lorenzo_dla", "@jesusg17"],
    "velaryonbloc": ["@Rozza1227"],
    "anydextestnt": ["@Ali_Raghami"],
    "teloskiwinzz": ["@TelosKiwi"],
    "blockbastrds": ["@mrquark28"],
}
